#!/usr/bin/bash

mount -t devtmpfs  devtmpfs  /dev
mount -t proc      proc      /proc
mount -t sysfs     sysfs     /sys
mount -t tmpfs     tmpfs     /tmp

# insert modules
while read -r mod_path
do
  insmod $mod_path
done < module_list.txt

# commandline arguments
args=$(cat /proc/cmdline)

# do your thing here, finally mount the boot location to /mnt/root










# clean up
umount /proc
umount /sys

# Boot
printf "\nBooting..."
exec switch_root /mnt/root /sbin/init
